version: '3.5'

networks:
  ablauf:

services:

  mysql:
    image: mysql:8.0
    networks:
      - ablauf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ablauf
      MYSQL_USER:     ablauf
      MYSQL_PASSWORD: ablauf
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
