name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: 'root'
        mysql database: 'ablauf'
        mysql user: 'ablauf'
        mysql password: 'ablauf'
    - name: Lint and test
      run: lein with-profile test do cljfmt check, difftest
      env:
        MARIA_JDBC_URI: "jdbc:mysql://root:root@127.0.0.1:3306/ablauf?serverTimezone=UTC"
