name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - uses: mirromutth/mysql-action@de1fba8b3f90ce8db80f663a7043be3cf3231248 # v1.1
      with:
        mysql root password: 'root'
        mysql database: 'ablauf'
        mysql user: 'ablauf'
        mysql password: 'ablauf'
    - name: Lint and test
      run: lein with-profile test do cljfmt check, difftest
      env:
        MARIA_JDBC_URI: "jdbc:mysql://root:root@127.0.0.1:3306/ablauf?serverTimezone=UTC"
